
#if !defined(RISCV_EMU_H)
#define RISCV_EMU_H
#include <stddef.h>
#include <stdint.h>
#include <stdbool.h>
#define RISCV_EMU_MMIO_START 0xF00C0000UL
#define RISCV_EMU_MMIO_SIZE 0xFFFF
#define RISCV_EMU_MMIO_END (RISCV_EMU_MMIO_START + RISCV_EMU_MMIO_SIZE)
#define RISCV_EMU_CONSOLE_MMIOADR (RISCV_EMU_MMIO_START + 0x10)
#define RISCV_EMU_CONSOLE_PRINT_CHAR8_ADR (RISCV_EMU_CONSOLE_MMIOADR + 0x00)
#define RISCV_EMU_CONSOLE_SCAN_CHAR8_ADR (RISCV_EMU_CONSOLE_MMIOADR + 0x01)
#define RISCV_EMU_CONSOLE_PRINT_INT32_ADR (RISCV_EMU_CONSOLE_MMIOADR + 0x10)
#define RISCV_EMU_CONSOLE_PRINT_UINT32_ADR (RISCV_EMU_CONSOLE_MMIOADR + 0x14)
#define RISCV_EMU_CONSOLE_PRINT_INT32_HEX_ADR (RISCV_EMU_CONSOLE_MMIOADR + 0x18)
#define RISCV_EMU_CONSOLE_PRINT_UINT32_HEX_ADR (RISCV_EMU_CONSOLE_MMIOADR + 0x1C)
#endif

